# Generated by Django 3.2.13 on 2022-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resumo_id_requisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='ano',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumo',
            name='entrada_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
